# Generated by Django 4.2 on 2024-07-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoxModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('imagem', models.FileField(blank=True, null=True, upload_to='media/infox/site')),
                ('missao', models.TextField()),
                ('visao', models.TextField()),
                ('valores', models.TextField()),
                ('tituloVideo', models.CharField(max_length=255)),
                ('descricaoVideo', models.TextField()),
                ('videoLink', models.TextField()),
                ('equipeImagem', models.FileField(blank=True, null=True, upload_to='media/infox/site')),
                ('linkMapa', models.TextField()),
            ],
        ),
    ]
