# Generated by Django 4.2 on 2024-07-15 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CursoSuper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('curso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='curso_super', to='infox.cursos')),
            ],
        ),
        migrations.CreateModel(
            name='LogoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_empresa', models.ImageField(blank=True, null=True, upload_to='media/infox/logos_empresas/')),
            ],
        ),
        migrations.CreateModel(
            name='Tutora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricaoTutora', models.TextField()),
                ('imagemTutora', models.ImageField(blank=True, null=True, upload_to='media/infox/')),
            ],
        ),
        migrations.CreateModel(
            name='PosGraduacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('curso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pos_graduacao', to='infox.cursos')),
            ],
        ),
        migrations.CreateModel(
            name='MBA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('curso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mba', to='infox.cursos')),
            ],
        ),
        migrations.CreateModel(
            name='CursoTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('curso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='curso_tecnico', to='infox.cursos')),
            ],
        ),
        migrations.CreateModel(
            name='CursoSuperior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituloS', models.CharField(max_length=255)),
                ('descricaoTituloS', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media/infox/logos/')),
                ('imagemCapa', models.ImageField(blank=True, null=True, upload_to='media/infox/')),
                ('cursos_super', models.ManyToManyField(blank=True, related_name='cursos_superiores', to='infox.cursosuper')),
            ],
        ),
    ]
