# Generated by Django 4.2 on 2024-07-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infox', '0002_cursos_cursosuper_logoempresa_tutora_posgraduacao_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogoEmpresa',
        ),
        migrations.DeleteModel(
            name='Tutora',
        ),
        migrations.RemoveField(
            model_name='cursosuperior',
            name='cursos_super',
        ),
        migrations.AddField(
            model_name='cursosuperior',
            name='descricaoTutora',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cursosuperior',
            name='imagemTutora',
            field=models.ImageField(blank=True, null=True, upload_to='media/infox/'),
        ),
        migrations.AddField(
            model_name='cursosuperior',
            name='logo_empresa',
            field=models.ImageField(blank=True, null=True, upload_to='media/infox/logos_empresas/'),
        ),
    ]
