# Generated by Django 4.2 on 2024-07-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infox', '0003_delete_logoempresa_delete_tutora_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogoEmpresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=255)),
                ('logo_empresa', models.ImageField(blank=True, null=True, upload_to='media/infox/logos_empresas/')),
            ],
        ),
        migrations.RemoveField(
            model_name='cursosuperior',
            name='logo_empresa',
        ),
    ]
