# Generated by Django 4.2 on 2024-07-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infox', '0004_logoempresas_remove_cursosuperior_logo_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursosuper',
            name='curso',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cursosuper',
            name='descricao',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cursotecnico',
            name='curso',
            field=models.CharField(max_length=255),
        ),
    ]
