# Generated by Django 4.2 on 2024-07-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infox', '0005_alter_cursosuper_curso_alter_cursosuper_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mba',
            name='curso',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='posgraduacao',
            name='curso',
            field=models.CharField(max_length=255),
        ),
    ]
