# Generated by Django 4.2 on 2024-07-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infox', '0006_alter_mba_curso_alter_posgraduacao_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoProf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('imagemLogo', models.FileField(blank=True, null=True, upload_to='media/infox/site')),
                ('imagemCapa', models.FileField(blank=True, null=True, upload_to='media/infox/site')),
            ],
        ),
        migrations.CreateModel(
            name='LogoEmpresasProf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=255)),
                ('logo_empresa', models.ImageField(blank=True, null=True, upload_to='media/infox/logos_empresas_prof/')),
            ],
        ),
    ]
