# Generated by Django 4.2 on 2024-07-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infox', '0007_cursoprof_logoempresasprof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursoprof',
            name='imagemCapa',
            field=models.FileField(blank=True, null=True, upload_to='media/infox/site/'),
        ),
        migrations.AlterField(
            model_name='cursoprof',
            name='imagemLogo',
            field=models.FileField(blank=True, null=True, upload_to='media/infox/site/'),
        ),
    ]
