# Generated by Django 4.2 on 2024-07-22 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infox', '0008_alter_cursoprof_imagemcapa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pacote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome do Pacote')),
                ('descricao', models.TextField(verbose_name='Descrição do Pacote')),
                ('cor_fundo', models.CharField(max_length=7, verbose_name='Cor de Fundo')),
                ('cor_curso', models.CharField(max_length=7, verbose_name='Cor do Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Curso')),
                ('pacote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='infox.pacote')),
            ],
        ),
    ]
