# Generated by Django 4.2 on 2024-07-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infox', '0009_pacote_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacote',
            name='cor_curso_tex',
            field=models.CharField(default=1, max_length=7, verbose_name='Cor do Texto Curso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacote',
            name='cor_fundo_tex',
            field=models.CharField(default=1, max_length=7, verbose_name='Cor de Texto Pacote'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pacote',
            name='cor_curso',
            field=models.CharField(max_length=7, verbose_name='Cor do Fundo Curso'),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='cor_fundo',
            field=models.CharField(max_length=7, verbose_name='Cor de Fundo Padote'),
        ),
    ]
