# Generated by Django 4.2 on 2024-07-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infox', '0010_pacote_cor_curso_tex_pacote_cor_fundo_tex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome do Curso'),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='cor_curso',
            field=models.CharField(max_length=200, verbose_name='Cor do Fundo Curso'),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='cor_curso_tex',
            field=models.CharField(max_length=200, verbose_name='Cor do Texto Curso'),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='cor_fundo',
            field=models.CharField(max_length=200, verbose_name='Cor de Fundo Padote'),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='cor_fundo_tex',
            field=models.CharField(max_length=200, verbose_name='Cor de Texto Pacote'),
        ),
    ]
