# Generated by Django 4.2 on 2024-07-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infox', '0011_alter_curso_nome_alter_pacote_cor_curso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cursoturma', models.CharField(max_length=255)),
                ('descricao_turma', models.TextField(verbose_name='Descrição do curso em turma')),
                ('foto_turma', models.ImageField(blank=True, null=True, upload_to='media/infox/')),
            ],
        ),
    ]
