# Generated by Django 4.2 on 2024-07-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infox', '0012_turma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipefoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipe', models.CharField(max_length=255)),
                ('foto_equipe', models.ImageField(blank=True, null=True, upload_to='media/infox/equipe')),
            ],
        ),
    ]
