# Generated by Django 4.2 on 2024-07-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infox', '0014_contactme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactme',
            name='message',
            field=models.TextField(max_length=2000),
        ),
    ]
