from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('aluno.urls')),
    path('', include('django.contrib.auth.urls')),
    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
    path("accounts/", include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),
    path('pedido/', include('pedido.urls')),
    path('perfil/', include('perfil.urls')),
    
    path('site/', views.site_detalhes, name='site_detalhes'),

    path('infox/<int:id>/', views.infox_detalhes, name='infox_detalhes'),
    path('infoxlista/<int:id>/', views.infox_lista, name='infox_lista'),
    path('infoxnovo/', views.infox_novo, name='infox_novo'),
    path('infoxupdate/<int:id>/', views.infox_update, name='infox_update'),
    path('infoxequinovo/', views.infox_equi_novo, name='infox_equi_novo'),
    path('infoxequilista/', views.infox_equi_lista, name='infox_equi_lista'),
    path('infoxequiupdate/<int:id>/', views.infox_equi_update, name='infox_equi_update'),
    path('infoxequidelete/<int:id>/', views.infox_equi_delete, name='infox_equi_delete'),

    path('contato/', views.contato_detalhes, name='contato_detalhes'),
    path('contatoenviado/', views.contato_enviado, name='contato_enviado'),
    
    path('superior/', views.superior_detalhes, name='superior_detalhes'),
    path('superiorlista/<int:id>/', views.superior_lista, name='superior_lista'),
    path('superiornovo/', views.superior_novo, name='superior_novo'),
    path('superiorupdate/<int:id>/', views.superior_update, name='superior_update'),
    path('superiorlogonovo/', views.superior_logo_novo, name='superior_logo_novo'),
    path('superiorlogolista', views.superior_logo_lista, name='superior_logo_lista'),
    path('superiorlogoupdate/<int:id>/', views.superior_logo_update, name='superior_logo_update'),
    path('superiorlogodelete/<int:id>/', views.superior_logo_delete, name='superior_logo_delete'),
    path('superiorsupernovo/', views.superior_super_novo, name='superior_super_novo'),
    path('superiorsuperlista/', views.superior_super_lista, name='superior_super_lista'),
    path('superiorsuperupdate/<int:id>/', views.superior_super_update, name='superior_super_update'),
    path('superiorsuperdelete/<int:id>/', views.superior_super_delete, name='superior_super_delete'),
    path('superiortecnovo/', views.superior_tec_novo, name='superior_tec_novo'),
    path('superiorteclista/', views.superior_tec_lista, name='superior_tec_lista'),
    path('superiortecupdate/<int:id>/', views.superior_tec_update, name='superior_tec_update'),
    path('superiortecdelete/<int:id>/', views.superior_tec_delete, name='superior_tec_delete'),
    path('superiorposnovo/', views.superior_pos_novo, name='superior_pos_novo'),
    path('superiorposlista/', views.superior_pos_lista, name='superior_pos_lista'),
    path('superiorposupdate/<int:id>/', views.superior_pos_update, name='superior_pos_update'),
    path('superiorposdelete/<int:id>/', views.superior_pos_delete, name='superior_pos_delete'),
    path('superiormbanovo/', views.superior_mba_novo, name='superior_mba_novo'),
    path('superiormbalista/', views.superior_mba_lista, name='superior_mba_lista'),
    path('superiormbaupdate/<int:id>/', views.superior_mba_update, name='superior_mba_update'),
    path('superiormbadelete/<int:id>/', views.superior_mba_delete, name='superior_mba_delete'),

    path('prof/', views.prof_detalhes, name='prof_detalhes'),
    path('profnovo/', views.prof_novo, name='prof_novo'),
    path('proflista/<int:id>/', views.prof_lista, name='prof_lista'),
    path('profupdate/<int:id>/', views.prof_update, name='prof_update'),
    path('proflogonovo/', views.prof_logo_novo, name='prof_logo_novo'),
    path('proflogolista', views.prof_logo_lista, name='prof_logo_lista'),
    path('proflogoupdate/<int:id>/', views.prof_logo_update, name='prof_logo_update'),
    path('proflogodelete/<int:id>/', views.prof_logo_delete, name='prof_logo_delete'),
    path('profpacotenovo/', views.prof_pacote_novo, name='prof_pacote_novo'),
    path('profpacotelista/', views.prof_pacote_lista, name='prof_pacote_lista'),
    path('profpacoteupdate/<int:id>/', views.prof_pacote_update, name='prof_pacote_update'),
    path('profpacotedelete/<int:id>/', views.prof_pacote_delete, name='prof_pacote_delete'),
    path('profcursonovo/', views.prof_curso_novo, name='prof_curso_novo'),
    path('profcursolista/', views.prof_curso_lista, name='prof_curso_lista'),
    path('profcursoupdate/<int:id>/', views.prof_curso_update, name='prof_curso_update'),
    path('profcursodelete/<int:id>/', views.prof_curso_delete, name='prof_curso_delete'),
    path('profturmanovo/', views.prof_turma_novo, name='prof_turma_novo'),
    path('profturmalista/', views.prof_turma_lista, name='prof_turma_lista'),
    path('profturmaupdate/<int:id>/', views.prof_turma_update, name='prof_turma_update'),
    path('profturmadelete/<int:id>/', views.prof_turma_delete, name='prof_turma_delete'),

    path('cursoson/', views.cursoson_detalhes, name='cursoson_detalhes'),
    path('cursosonindiv/<int:id>/', views.cursoson_indivi, name='cursoson_indivi'),
    path('cursosondig/', views.cursoson_dig, name='cursoson_dig'),
    
]
