# Generated by Django 4.2 on 2023-08-02 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('cpf', models.CharField(blank=True, max_length=255, null=True)),
                ('foto', models.ImageField(upload_to='media/aluno/foto')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('horas', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('basico', 'Básico'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado')], default='basico', max_length=13)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='media/curso/capa')),
                ('selo', models.ImageField(blank=True, null=True, upload_to='media/curso/selo')),
                ('selo_cinza', models.ImageField(blank=True, null=True, upload_to='media/curso/selo')),
                ('selo_prova', models.ImageField(blank=True, null=True, upload_to='media/curso/selo')),
                ('selo_prova_cinza', models.ImageField(blank=True, null=True, upload_to='media/curso/selo')),
                ('selo_max', models.ImageField(blank=True, null=True, upload_to='media/curso/selo')),
                ('selo_cinza_max', models.ImageField(blank=True, null=True, upload_to='media/curso/selo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Digitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField()),
                ('descricao', models.TextField()),
                ('repeticao', models.IntegerField()),
                ('licao', models.CharField(max_length=255)),
                ('fase', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], default='1', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('data_resposta', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluno.aluno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluno.curso')),
            ],
        ),
        migrations.CreateModel(
            name='RelatorioDigitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licao_atual', models.IntegerField()),
                ('data_acesso', models.DateTimeField(auto_now_add=True)),
                ('toques', models.IntegerField()),
                ('acertos', models.DecimalField(decimal_places=2, max_digits=6)),
                ('erros', models.IntegerField()),
                ('tempo', models.CharField(max_length=255)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField()),
                ('tipo', models.CharField(choices=[('checks', 'Checks'), ('radios', 'Radios')], max_length=10)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluno.curso')),
            ],
        ),
        migrations.CreateModel(
            name='ProvaDigitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_conclusao', models.DateTimeField(auto_now_add=True)),
                ('toques', models.IntegerField(blank=True, null=True)),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('tempo', models.CharField(blank=True, max_length=255, null=True)),
                ('erros', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Licao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('video', models.TextField()),
                ('botao', models.FileField(blank=True, null=True, upload_to='media/curso/downloads')),
                ('ordem', models.IntegerField()),
                ('categoria', models.CharField(max_length=200)),
                ('categoria_ordem', models.IntegerField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluno.curso')),
            ],
        ),
        migrations.CreateModel(
            name='ItemQuestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
                ('correto', models.BooleanField()),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluno.questao')),
            ],
        ),
        migrations.CreateModel(
            name='InscricaoDigitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licao_atual', models.IntegerField(default='1')),
                ('contador_licao', models.IntegerField(default='0')),
                ('data_inscricao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_acesso', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('digitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluno.digitacao')),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluno.curso')),
            ],
        ),
        migrations.CreateModel(
            name='ConclusaoLicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('fazer', 'Fazer'), ('concluido', 'Concluido')], default='fazer', max_length=9)),
                ('data_conclusao', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluno.curso')),
                ('licao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluno.licao')),
            ],
        ),
    ]
