# Generated by Django 4.2 on 2023-10-16 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='categoria_licao',
            field=models.IntegerField(default='0'),
        ),
    ]
