# Generated by Django 4.2 on 2024-07-05 14:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aluno', '0002_inscricao_categoria_licao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='categoria_licao',
            field=models.IntegerField(default='1'),
        ),
    ]
