# Generated by Django 4.2 on 2024-07-12 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0004_infoxmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InfoxModel',
        ),
    ]
