# Generated by Django 4.2 on 2024-07-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0005_delete_infoxmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='cadastro_completo',
            field=models.BooleanField(default=False),
        ),
    ]
