# Generated by Django 4.2 on 2024-08-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0006_aluno_cadastro_completo'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='descricao_curta',
            field=models.CharField(default=1, max_length=180),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
