# Generated by Django 4.2 on 2024-08-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0009_digitacaodetalhes'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitacaodetalhes',
            name='descricao',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='digitacaodetalhes',
            name='descricao_curta',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='digitacaodetalhes',
            name='nome',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
