# Generated by Django 4.2 on 2024-08-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0010_digitacaodetalhes_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licao',
            name='demo',
            field=models.BooleanField(default=False),
        ),
    ]
