# Generated by Django 4.2 on 2024-08-30 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0011_licao_demo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licao',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licoes', to='aluno.curso'),
        ),
    ]
