# Generated by Django 4.2 on 2024-09-02 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0012_alter_licao_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licao',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluno.curso'),
        ),
    ]
