# Generated by Django 4.2 on 2024-09-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0015_remove_aluno_tour_completo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='tour_completo',
            field=models.BooleanField(default=False),
        ),
    ]
