# Generated by Django 4.2 on 2024-09-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0016_aluno_tour_completo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='genero',
            field=models.CharField(choices=[('H', 'Homem'), ('M', 'Mulher'), ('O', 'Outros')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='tour_completo',
            field=models.BooleanField(default=True),
        ),
    ]
