# Generated by Django 4.2 on 2024-09-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0017_aluno_genero_alter_aluno_tour_completo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='tour_dig_completo',
            field=models.BooleanField(default=True),
        ),
    ]
