# Generated by Django 4.2 on 2024-10-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0018_aluno_tour_dig_completo'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='video_curso',
            field=models.CharField(default=1, max_length=800),
            preserve_default=False,
        ),
    ]
