# Generated by Django 4.2 on 2024-08-06 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aluno', '0007_curso_descricao_curta_curso_preco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCarrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('carrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido.carrinho')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluno.curso')),
            ],
        ),
        migrations.AddField(
            model_name='carrinho',
            name='cursos',
            field=models.ManyToManyField(through='pedido.ItemCarrinho', to='aluno.curso'),
        ),
        migrations.AddField(
            model_name='carrinho',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
